export const API_URL = `${
  process.env.NODE_ENV === 'production' ? process.env.REACT_APP_API_URL : ''
}`;

export const GET_HEALTH = 'GET_HEALTH';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_COGNITO_USER = 'SET_COGNITO_USER';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const CLEAN_AUTH_STATE = 'CLEAN_AUTH_STATE';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const LOGOUT = 'LOGOUT';
export const GET_CREDENTIALS = 'GET_CREDENTIALS';
export const SET_CREDENTIALS = 'SET_CREDENTIALS';

export const SET_LOCATION = 'SET_LOCATION';
export const CREATE_LOCATION_LOG = 'CREATE_LOCATION_LOG';
export const GET_LOCATION_LOGS = 'GET_LOCATION_LOGS';
export const SET_LOCATION_LOGS = 'SET_LOCATION_LOGS';

export default {
  GET_HEALTH,
  LOGIN,
  LOGIN_SUCCESS,
  FETCH_CURRENT_USER,
  SET_NEW_PASSWORD,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  SET_CURRENT_USER,
  SET_COGNITO_USER,
  SET_AUTH_STATUS,
  CLEAN_AUTH_STATE,
  SET_AUTH_ERROR,
  SET_USER_ERROR,
  LOGOUT,
  GET_CREDENTIALS,
  SET_CREDENTIALS,
  SET_LOCATION,
  CREATE_LOCATION_LOG,
  GET_LOCATION_LOGS,
  SET_LOCATION_LOGS,
};
